import { PrismaClient } from '@prisma/client';
import { idMap } from '@graphql/idMap';

export default async function seedStonesOnProjects(prisma: PrismaClient): Promise<void> {
  await prisma.stonesOnProject.createMany({
    data: [
      {
        projectId: idMap.projects.WDC_2021_PP_INTRO,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 4431,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INTRO,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 1945,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INTRO,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1726,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INTRO,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 641,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INTRO,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1527,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 32,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 57,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 21,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.GROEN_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 204,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 134,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.BLAUW_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 3427,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.BLAUW_LP_E,
        userId: idMap.users.DDT_ADMIN,
        amount: 8967,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.PAARS_LP_D,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 9,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 56,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 377,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.IVOOR_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 15,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 694,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 341,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.BRUIN_LP_C,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 821,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 1213,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.GRIJS_LP_B,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 867,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 2051,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 218,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 25,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        stoneId: idMap.stones.BLAUW_BK_C,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 631,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 11,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 305,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 2982,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 364,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.TURQUOISE_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 903,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 860,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.IVOOR_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 6000,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1099,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 7,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TINKER_BELL,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 408,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_TREASURE_MAP,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 500,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TREASURE_MAP,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 4700,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_TREASURE_MAP,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 3000,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_INDIAN_VILLAGE,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 229,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INDIAN_VILLAGE,
        stoneId: idMap.stones.ROOD_LP_C,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 118,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INDIAN_VILLAGE,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 132,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INDIAN_VILLAGE,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 43,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INDIAN_VILLAGE,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 96,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INDIAN_VILLAGE,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1693,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INDIAN_VILLAGE,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 66,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_INDIAN_VILLAGE,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 287,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 124,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.ROOD_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 7,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 622,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 499,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 248,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 696,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.TURQUOISE_LP_C,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 591,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 1062,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.BLAUW_LP_E,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 2157,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.BLAUW_LP_E,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 186,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.PAARS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 412,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.PAARS_LP_C,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 931,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.PAARS_LP_D,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 1331,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.ROZE_LP_A,
        userId: idMap.users.BART_VRIENS,
        amount: 2232,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.BART_VRIENS,
        amount: 636,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1046,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 10,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1747,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.GRIJS_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 355,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 697,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_MERMAIDS,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 131,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_SKULL_ISLAND,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 990,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_SKULL_ISLAND,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 694,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_SKULL_ISLAND,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1900,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_SKULL_ISLAND,
        stoneId: idMap.stones.GRIJS_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 772,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_SKULL_ISLAND,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 748,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_FOOT_STEPS,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 1560,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FOOT_STEPS,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 240,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 716,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.ROOD_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 496,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 36,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.GROEN_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 2304,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 904,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 9124,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.PAARS_LP_C,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 340,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.PAARS_LP_D,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 372,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 788,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 468,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 790,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 1326,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 336,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_LOST_BOYS,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 96,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 341,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.ROOD_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 1898,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 172,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 784,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 21,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 761,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 943,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.PAARS_LP_C,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 2051,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.PAARS_LP_D,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 877,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 962,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 326,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 809,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 351,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 917,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 3683,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 369,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FIGHT,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 815,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 569,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 38,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.ORANJE_LP_B,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 67,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 21,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 57,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 349,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 3500,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 745,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.GROEN_LP_E,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 794,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.TURQUOISE_LP_A,
        userId: idMap.users.BART_VRIENS,
        amount: 1060,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 217,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.ROZE_LP_D,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 735,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 21,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1658,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 356,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_CROCODILE,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 131,
      },

      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_SHIP,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 11487,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_SHIP,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 9432,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_SHIP,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 6770,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_SHIP,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 3954,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_SHIP,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 3631,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_SHIP,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1787,
      },
      {
        projectId: idMap.projects.WDC_2021_PP_FLYING_SHIP,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 1888,
      },
    ],
  });
}
