overwrite: true
generates:
  ./src/graphql/__generated__/codegen-self.ts:
    schema: ${API_ROOT_SELF}
    documents: ./src/graphql/*/{queries,mutations}-self.graphql
    plugins:
      - typescript
      - typescript-operations
      - typescript-graphql-request
      - plugin-typescript-swr
    config:
      namingConvention: keep
      skipTypename: true
      avoidOptionals: true
