overwrite: true
schema: ./schema.graphql
documents: ./src/graphql/*/{queries,mutations}.graphql
# hooks:
#   afterAllFileWrite:
#     - yarn lint
generates:
  ./src/graphql/__generated__/introspection.json:
    plugins:
      - urql-introspection
    config:
      module: es2015
      includeScalars: true
      includeEnums: true
      includeInputs: true
  ./src/graphql/__generated__/codegen.tsx:
    plugins:
      - typescript
    config:
      namingConvention: keep
      skipTypename: true
  ./src/graphql/:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: __generated__/codegen.tsx
      folder: __generated__
      extension: .ts
    plugins:
      - typescript-operations
      - typescript-urql
    config:
      namingConvention: keep
      skipTypename: true

      # TODO https://www.graphql-code-generator.com/plugins/typescript-urql
      # urqlImportFrom: ./TODO
      # scalars: TODO
