projects:
  self:
    schema: schema.graphql
    documents: ./src/graphql/*/{queries,mutations}-self.graphql
    extensions:
      endpoints:
        default:
          url: http://localhost:3000/api/graphql
          headers:
            Authorization: Bearer 99584a51d94805e65b3f51ff36e614d5f8acb9e07e65911c9e98ffd1c2d2a948
