import { PrismaClient } from '@prisma/client';
import { idMap } from '@graphql/idMap';

export default async function seedStonesOnProjects(prisma: PrismaClient): Promise<void> {
  await prisma.stonesOnProjectPart.createMany({
    data: [
      {
        projectPartId: idMap.events.WDC_2021.INTRODUCTION.DON_DOMINO.FIELD,
        stoneId: idMap.stones.ROOD_DO_A,
        userId: idMap.users.DON_DOMINO,
        amount: 1766,
      },
      {
        projectPartId: idMap.events.WDC_2021.INTRODUCTION.DON_DOMINO.FIELD,
        stoneId: idMap.stones.GEEL_DO_A,
        userId: idMap.users.DON_DOMINO,
        amount: 1517,
      },
      {
        projectPartId: idMap.events.WDC_2021.INTRODUCTION.DON_DOMINO.FIELD,
        stoneId: idMap.stones.ZWART_DO_A,
        userId: idMap.users.DON_DOMINO,
        amount: 729,
      },
      {
        projectPartId: idMap.events.WDC_2021.INTRODUCTION.DON_DOMINO.FIELD,
        stoneId: idMap.stones.WIT_DO_A,
        userId: idMap.users.DON_DOMINO,
        amount: 638,
      },

      {
        projectPartId: idMap.events.WDC_2021.INTRODUCTION.SINNERS.FIELD,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 1915,
      },
      {
        projectPartId: idMap.events.WDC_2021.INTRODUCTION.SINNERS.FIELD,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 710,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.INTRO.FIELD,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 4431,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.INTRO.FIELD,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 1945,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.INTRO.FIELD,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1726,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.INTRO.FIELD,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 641,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.INTRO.FIELD,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1527,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 32,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 57,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 21,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.GROEN_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 204,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 134,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.BLAUW_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 3427,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.BLAUW_LP_E,
        userId: idMap.users.DDT_ADMIN,
        amount: 8967,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.PAARS_LP_D,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 9,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 56,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 377,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.IVOOR_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 15,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 694,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 341,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.BRUIN_LP_C,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 821,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 1213,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.GRIJS_LP_B,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 867,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 2051,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 218,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 25,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        stoneId: idMap.stones.BLAUW_BK_C,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 631,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 11,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 305,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 2982,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 364,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.TURQUOISE_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 903,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 860,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.IVOOR_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 6000,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1099,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 7,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 408,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MAP,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 500,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MAP,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 4700,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MAP,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 3000,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.INDIAN_VILLAGE,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 229,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.INDIAN_VILLAGE,
        stoneId: idMap.stones.ROOD_LP_C,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 118,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.INDIAN_VILLAGE,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 132,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.INDIAN_VILLAGE,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 43,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.INDIAN_VILLAGE,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 96,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.INDIAN_VILLAGE,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1693,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.INDIAN_VILLAGE,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 66,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.INDIAN_VILLAGE,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 287,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 124,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.ROOD_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 7,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 622,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 499,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 248,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 696,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.TURQUOISE_LP_C,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 591,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 1062,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.BLAUW_LP_E,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 2157,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.BLAUW_LP_E,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 186,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.PAARS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 412,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.PAARS_LP_C,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 931,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.PAARS_LP_D,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 1331,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.ROZE_LP_A,
        userId: idMap.users.BART_VRIENS,
        amount: 2232,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.BART_VRIENS,
        amount: 636,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1046,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 10,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1747,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.GRIJS_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 355,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 697,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 131,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.SKULL_ISLAND,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 990,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.SKULL_ISLAND,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 694,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.SKULL_ISLAND,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1900,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.SKULL_ISLAND,
        stoneId: idMap.stones.GRIJS_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 772,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.SKULL_ISLAND,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 748,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.FOOT_STEPS,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 1560,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.FOOT_STEPS,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 240,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 716,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.ROOD_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 496,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 36,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.GROEN_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 2304,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 904,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.BLAUW_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 9124,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.PAARS_LP_C,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 340,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.PAARS_LP_D,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 372,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 788,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 468,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 790,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 1326,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 336,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 96,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 341,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.ROOD_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 1898,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 172,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 784,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 21,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 761,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 943,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.PAARS_LP_C,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 2051,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.PAARS_LP_D,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 877,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 962,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 326,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 809,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 351,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.GRIJS_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 917,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 3683,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 369,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 815,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.ROOD_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 569,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 38,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.ORANJE_LP_B,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 67,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 21,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 57,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.GROEN_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 349,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 3500,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.GROEN_LP_D,
        userId: idMap.users.DDT_ADMIN,
        amount: 745,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.GROEN_LP_E,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 794,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.TURQUOISE_LP_A,
        userId: idMap.users.BART_VRIENS,
        amount: 1060,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.ROZE_LP_C,
        userId: idMap.users.DDT_ADMIN,
        amount: 217,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.ROZE_LP_D,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 735,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.BRUIN_LP_B,
        userId: idMap.users.WASILJA_PETERSE,
        amount: 21,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1658,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.WIT_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 356,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 131,
      },

      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_SHIP.FIELD,
        stoneId: idMap.stones.ORANJE_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 11487,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_SHIP.FIELD,
        stoneId: idMap.stones.GEEL_LP_A,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 9432,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_SHIP.FIELD,
        stoneId: idMap.stones.GEEL_LP_B,
        userId: idMap.users.DDT_ADMIN,
        amount: 6770,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_SHIP.FIELD,
        stoneId: idMap.stones.IVOOR_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 3954,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_SHIP.FIELD,
        stoneId: idMap.stones.BRUIN_LP_A,
        userId: idMap.users.JAAP_VERSCHUREN,
        amount: 3631,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_SHIP.FIELD,
        stoneId: idMap.stones.ZWART_LP_A,
        userId: idMap.users.DDT_ADMIN,
        amount: 1787,
      },
      {
        projectPartId: idMap.events.WDC_2021.PETER_PAN.FLYING_SHIP.FIELD,
        stoneId: idMap.stones.WIT_LP_B,
        userId: idMap.users.WIM_VAN_OTTERDIJK,
        amount: 1888,
      },
    ],
  });
}
