import { PrismaClient, ProjectStatus, ProjectType } from '@prisma/client';
import { idMap } from '@graphql/idMap';
import { generateSlug } from '@lib/util';

export default async function seedProjects(prisma: PrismaClient): Promise<void> {
  await prisma.project.createMany({
    data: [
      {
        id: idMap.projects.VEXX_WIX,
        name: 'WIX Logo',
        slug: generateSlug('Wix'),
        description: '',
        number: 0,
        subNumber: 1,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_DOODLE,
        name: 'Doodle',
        slug: generateSlug('Doodle'),
        description: '',
        number: 1,
        subNumber: 1,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_CAMPBELL,
        name: "Campbell's Soup",
        slug: generateSlug("Campbell's Soup"),
        description: '',
        number: 2,
        subNumber: 1,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_MATISSE,
        name: 'Matisse - The Dance',
        slug: generateSlug('Matisse - The Dance'),
        description: '',
        number: 2,
        subNumber: 2,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_VAN_GOGH,
        name: 'Van Gogh',
        slug: generateSlug('Van Gogh'),
        description: '',
        number: 2,
        subNumber: 3,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_ELMO,
        name: 'Elmo',
        slug: generateSlug('Elmo'),
        description: '',
        number: 3,
        subNumber: 1,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_SPONGEBOB,
        name: 'Spongebob',
        slug: generateSlug('Spongebob'),
        description: '',
        number: 3,
        subNumber: 2,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BOOK,
        name: 'Book',
        slug: generateSlug('Book'),
        description: '',
        number: 0,
        subNumber: 0,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.INTRODUCTION,
        supervisorId: idMap.users.WIM_VAN_OTTERDIJK,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.projects.WDC_2021_DON_DOMINO,
        name: 'Don Domino Sponsor Field',
        slug: generateSlug('DonDomino'),
        description: '',
        number: 22,
        subNumber: 0,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.INTRODUCTION,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_SINNERS,
        name: 'Sinners Sponsor Field',
        slug: generateSlug('Sinners'),
        description: '',
        number: 23,
        subNumber: 0,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.INTRODUCTION,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_INTRO,
        name: 'Peter Pan Intro Field',
        slug: generateSlug('Peter Pan Intro'),
        description: '',
        number: 1,
        subNumber: 0,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        name: 'Main Characters Flying Over London',
        slug: generateSlug('Flying London'),
        description: '',
        number: 2,
        subNumber: 0,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_SKULL_ISLAND,
        name: 'Skull Island',
        slug: generateSlug('Skull Island'),
        description: '',
        number: 5,
        subNumber: 4,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.BART_VRIENS,
        type: ProjectType.WALL_CUBE,
      },
      {
        id: idMap.projects.WDC_2021_BATB_INTRO,
        name: 'Beauty and the Beast Intro Field',
        slug: generateSlug('Beauty and the Beast Intro'),
        description: '',
        number: 15,
        subNumber: 0,
        status: ProjectStatus.BUILT,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
    ],
  });
}
