import { PrismaClient, ProjectStatus, ProjectType } from '@prisma/client';
import { idMap } from '@graphql/idMap';
import { generateSlug } from '@lib/util';

export default async function seedProjects(prisma: PrismaClient): Promise<void> {
  await prisma.project.createMany({
    data: [
      // VEXX
      {
        id: idMap.projects.VEXX_WIX,
        name: 'WIX Logo',
        slug: generateSlug('Wix'),
        description: '',
        number: 0,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_DOODLE,
        name: 'Doodle',
        slug: generateSlug('Doodle'),
        description: '',
        number: 1,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_CAMPBELL,
        name: "Campbell's Soup",
        slug: generateSlug("Campbell's Soup"),
        description: '',
        number: 2,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_MATISSE,
        name: 'Matisse - The Dance',
        slug: generateSlug('Matisse - The Dance'),
        description: '',
        number: 2,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_VAN_GOGH,
        name: 'Van Gogh',
        slug: generateSlug('Van Gogh'),
        description: '',
        number: 2,
        subNumber: 3,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_ELMO,
        name: 'Elmo',
        slug: generateSlug('Elmo'),
        description: '',
        number: 3,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.VEXX_SPONGEBOB,
        name: 'Spongebob',
        slug: generateSlug('Spongebob'),
        description: '',
        number: 3,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.VEXX_PROJECT,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },

      // WDC 2021
      {
        id: idMap.projects.WDC_2021_BOOK,
        name: 'Book',
        slug: generateSlug('Book'),
        description: '',
        number: 0,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.INTRODUCTION,
        supervisorId: idMap.users.WIM_VAN_OTTERDIJK,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.projects.WDC_2021_DON_DOMINO,
        name: 'Don Domino Sponsor Field',
        slug: generateSlug('DonDomino'),
        description: '',
        number: 22,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.INTRODUCTION,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_SINNERS,
        name: 'Sinners Sponsor Field',
        slug: generateSlug('Sinners'),
        description: '',
        number: 23,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.INTRODUCTION,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_INTRO,
        name: 'Peter Pan Intro Field',
        slug: generateSlug('Peter Pan Intro'),
        description: '',
        number: 1,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_FLYING_LONDON,
        name: 'Main Characters Flying Over London',
        slug: generateSlug('Flying London'),
        description: '',
        number: 2,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_NEVERLAN,
        name: 'Neverland',
        slug: generateSlug('Neverland'),
        description: '',
        number: 3,
        subNumber: 0,
        status: ProjectStatus.CANCELLED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.BART_VRIENS,
        type: ProjectType.STRUCTURE,
      },
      {
        id: idMap.projects.WDC_2021_PP_TINKER_BELL,
        name: 'Tinker Bell',
        slug: generateSlug('Tinker Bell'),
        description: '',
        number: 4,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_TREASURE_MAP,
        name: 'Treasure Map',
        slug: generateSlug('Treasure Map'),
        description: '',
        number: 5,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.BART_VRIENS,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.projects.WDC_2021_PP_INDIAN_VILLAGE,
        name: 'Indian Village',
        slug: generateSlug('Indian Village'),
        description: '',
        number: 5,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.projects.WDC_2021_PP_MERMAIDS,
        name: 'Mermaids',
        slug: generateSlug('Mermaids'),
        description: '',
        number: 5,
        subNumber: 3,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_SKULL_ISLAND,
        name: 'Skull Island',
        slug: generateSlug('Skull Island'),
        description: '',
        number: 5,
        subNumber: 4,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.BART_VRIENS,
        type: ProjectType.WALL_CUBE,
      },
      {
        id: idMap.projects.WDC_2021_PP_FOOT_STEPS,
        name: 'Foot Steps',
        slug: generateSlug('Foot Steps'),
        description: '',
        number: 5,
        subNumber: 5,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.BART_VRIENS,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.projects.WDC_2021_PP_HIDING,
        name: 'Lost Boys Hiding Place',
        slug: generateSlug('Lost Boys Hiding Place'),
        description: '',
        number: 6,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.WIM_VAN_OTTERDIJK,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.projects.WDC_2021_PP_LOST_BOYS,
        name: 'The Lost Boys',
        slug: generateSlug('The Lost Boys'),
        description: '',
        number: 6,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_PP_FIGHT,
        name: 'Peter Pan vs. Captain Hook',
        slug: generateSlug('Peter Pan vs. Captain Hook'),
        description: '',
        number: 7,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_CROCODILE,
        name: 'Crocodile',
        slug: generateSlug('Crocodile'),
        description: '',
        number: 7,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_PP_FLYING_SHIP,
        name: 'Flying Ship',
        slug: generateSlug('Flying Ship'),
        description: '',
        number: 8,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.PETER_PAN,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_INTRO,
        name: "Emperor's New Clothes Intro",
        slug: generateSlug("Emperor's New Clothes Intro"),
        description: '',
        number: 9,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_CITY_RICH,
        name: 'Rich City',
        slug: generateSlug('Rich City'),
        description: '',
        number: 10,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_CITY_POOR,
        name: 'Poor City',
        slug: generateSlug('Poor City'),
        description: '',
        number: 10,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_DRESSER,
        name: 'Dresser',
        slug: generateSlug('Dresser'),
        description: '',
        number: 11,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.WIM_VAN_OTTERDIJK,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.projects.WDC_2021_ENC_CLOTHES,
        name: 'Clothes',
        slug: generateSlug('Clothes'),
        description: '',
        number: 11,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_ENC_EMPEROR,
        name: 'Emperor',
        slug: generateSlug('Emperor'),
        description: '',
        number: 12,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_EMPTY_FIELD,
        name: 'Empty Field',
        slug: generateSlug('Empty Field'),
        description: '',
        number: 13,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_SCISSORS,
        name: 'Scissors',
        slug: generateSlug('Scissors'),
        description: '',
        number: 13,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.WOUT_DUTOIT,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_PINCUSHION,
        name: 'Pincushion',
        slug: generateSlug('Pincushion'),
        description: '',
        number: 13,
        subNumber: 3,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.WOUT_DUTOIT,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_MEASURING_TAPE,
        name: 'Measuring Tape',
        slug: generateSlug('Measuring Tape'),
        description: '',
        number: 13,
        subNumber: 4,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.projects.WDC_2021_ENC_SPOOLS,
        name: 'Spools',
        slug: generateSlug('Spools'),
        description: '',
        number: 13,
        subNumber: 5,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_HOUSES,
        name: 'Background Houses',
        slug: generateSlug('Background Houses'),
        description: '',
        number: 14,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_ENC_SPECTATORS,
        name: 'Spectators',
        slug: generateSlug('Spectators'),
        description: '',
        number: 14,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_ENC_PARADE,
        name: 'Parade',
        slug: generateSlug('Parade'),
        description: '',
        number: 14,
        subNumber: 3,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.EMPERORS_NEW_CLOTHES,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_INTRO,
        name: 'Beauty and the Beast Intro Field',
        slug: generateSlug('Beauty and the Beast Intro'),
        description: '',
        number: 15,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },

      {
        id: idMap.projects.WDC_2021_BATB_STAINED_GLASS,
        name: 'Stained Glass Curse',
        slug: generateSlug('Stained Glass Curse'),
        description: '',
        number: 15,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_ROSE,
        name: 'Rose',
        slug: generateSlug('Rose'),
        description: '',
        number: 16,
        subNumber: 0,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WIM_VAN_OTTERDIJK,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.projects.WDC_2021_BATB_TRILOGY_1,
        name: 'Father Captured in Dungeon',
        slug: generateSlug('Father Captured in Dungeon'),
        description: '',
        number: 18,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_TRILOGY_2,
        name: 'Father Released, Belle Staying',
        slug: generateSlug('Father Released, Belle Staying'),
        description: '',
        number: 18,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_TRILOGY_3,
        name: 'Belle Crying in the Dungeon',
        slug: generateSlug('Belle Crying in the Dungeon'),
        description: '',
        number: 18,
        subNumber: 3,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_DINNER_CLOCK,
        name: 'Dinner - Living Clock',
        slug: generateSlug('Dinner - Living Clock'),
        description: '',
        number: 19,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_BATB_DINNER_TEAPOT,
        name: 'Dinner - Living Teapot',
        slug: generateSlug('Dinner - Living Teapot'),
        description: '',
        number: 19,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_BATB_DINNER_TEACUP,
        name: 'Dinner - Living Teacup',
        slug: generateSlug('Dinner - Living Teacup'),
        description: '',
        number: 19,
        subNumber: 3,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_BATB_DINNER_PLUMEAU,
        name: 'Dinner - Plumeau',
        slug: generateSlug('Dinner - Plumeau'),
        description: '',
        number: 19,
        subNumber: 4,
        status: ProjectStatus.CANCELLED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_BATB_DINNER_LUMIERE,
        name: 'Dinner - Lumiere',
        slug: generateSlug('Dinner - Lumiere'),
        description: '',
        number: 19,
        subNumber: 5,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_DINNER_TABLE,
        name: 'Dinner - Table',
        slug: generateSlug('Dinner - Table'),
        description: '',
        number: 19,
        subNumber: 6,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_DINNER_FOOD,
        name: 'Dinner - Plates of Food',
        slug: generateSlug('Dinner - Plates of Food'),
        description: '',
        number: 19,
        subNumber: 7,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.projects.WDC_2021_BATB_TREES,
        name: 'Background Trees',
        slug: generateSlug('Background Trees'),
        description: '',
        number: 20,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_BATB_WOLVES_DECOR,
        name: 'Wolves (painted)',
        slug: generateSlug('Wolves'),
        description: '',
        number: 20,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WIM_VAN_OTTERDIJK,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.projects.WDC_2021_BATB_FIGHT,
        name: 'Fight Beast vs. Wolf',
        slug: generateSlug('Fight Beast vs. Wolf'),
        description: '',
        number: 20,
        subNumber: 3,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_HEART,
        name: 'Heart',
        slug: generateSlug('Heart'),
        description: '',
        number: 20,
        subNumber: 4,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FALLWALL,
      },
      {
        id: idMap.projects.WDC_2021_BATB_WOLVES,
        name: 'Wolves',
        slug: generateSlug('Wolves'),
        description: '',
        number: 20,
        subNumber: 5,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.PIM_VRIENS,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_DANCE,
        name: 'Belle and Beast Dance',
        slug: generateSlug('Belle and Beast Dance'),
        description: '',
        number: 21,
        subNumber: 1,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.projects.WDC_2021_BATB_PILARS_DECOR,
        name: 'Pilars and Ribbons',
        slug: generateSlug(''),
        description: '',
        number: 21,
        subNumber: 2,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WIM_VAN_OTTERDIJK,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.projects.WDC_2021_BATB_PILARS,
        name: 'Pilars Concealment',
        slug: generateSlug('Pilars Concealment'),
        description: '',
        number: 21,
        subNumber: 3,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WIM_VAN_OTTERDIJK,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_BATB_BALLROOM_BACKGROUND,
        name: 'Ballroom Background',
        slug: generateSlug('Ballroom Background'),
        description: '',
        number: 21,
        subNumber: 4,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.projects.WDC_2021_BATB_BALLROOM_FLOOR,
        name: 'Ballroom Floor',
        slug: generateSlug('Ballroom Floor'),
        description: '',
        number: 21,
        subNumber: 5,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WASILJA_PETERSE,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.projects.WDC_2021_BATB_CHANDELIER,
        name: 'Chandelier',
        slug: generateSlug('Chandelier'),
        description: '',
        number: 21,
        subNumber: 6,
        status: ProjectStatus.COUNTED,
        subthemeId: idMap.subthemes.BEAUTY_AND_THE_BEAST,
        supervisorId: idMap.users.WIM_VAN_OTTERDIJK,
        type: ProjectType.DECOR,
      },
    ],
  });
}
