import { PrismaClient } from '@prisma/client';
import { idMap } from '@graphql/idMap';

// SELECT sl.stone_list_id, CONCAT(u.user_firstname, ' ', u.user_lastname), c.color_name, sl.stone_list_amount FROM `stone_lists` sl
// LEFT JOIN colors c ON c.color_id = sl.color_id
// LEFT JOIN users u ON u.user_id = sl.user_id
// WHERE stone_list_amount > 0
// ORDER BY u.user_id ASC, c.collection_id ASC, c.color_order ASC

// str.split('\n').map((line) => {
//   const l = line.split('\t');
//   console.log(line, l);
//   return `{userId: idMap.users.${l[1].replace(/\s/g, '_').toUpperCase()}, stoneId: idMap.stones.${l[2].replace(/\s|-/g, '_').toUpperCase()}, amount: ${l[3]}}`;
// }).join(',')

export default async function seedStoneInventory(prisma: PrismaClient): Promise<void> {
  await prisma.stoneInventory.createMany({
    data: [
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.ROOD_LP_D, amount: 792 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.GEEL_LP_B, amount: 1666 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.GROEN_LP_B, amount: 1636 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.GROEN_LP_C, amount: 730 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.TURQUOISE_LP_B, amount: 908 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.BLAUW_LP_A, amount: 1314 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.BLAUW_LP_D, amount: 897 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.IVOOR_LP_C, amount: 771 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.GRIJS_LP_A, amount: 595 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.ZWART_LP_A, amount: 908 },
      { userId: idMap.users.WILLIAM_FORD, stoneId: idMap.stones.WIT_LP_B, amount: 636 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ROOD_LP_A, amount: 1093 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ROOD_LP_B, amount: 712 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ROOD_LP_D, amount: 3224 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ORANJE_LP_B, amount: 2411 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ORANJE_LP_D, amount: 765 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ORANJE_LP_E, amount: 496 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.GEEL_LP_A, amount: 1039 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.GEEL_LP_B, amount: 1280 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.GROEN_LP_A, amount: 1106 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.GROEN_LP_C, amount: 2800 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.GROEN_LP_E, amount: 1996 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.TURQUOISE_LP_C, amount: 3375 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BLAUW_LP_C, amount: 2642 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BLAUW_LP_E, amount: 2187 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.PAARS_LP_C, amount: 1349 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.PAARS_LP_D, amount: 2680 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ROZE_LP_B, amount: 1365 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ROZE_LP_C, amount: 935 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ROZE_LP_D, amount: 716 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.IVOOR_LP_A, amount: 3218 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BRUIN_LP_A, amount: 1097 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BRUIN_LP_B, amount: 2053 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BRUIN_LP_C, amount: 762 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BRUIN_LP_D, amount: 549 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.GRIJS_LP_A, amount: 2388 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.GRIJS_LP_B, amount: 1020 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.GRIJS_LP_C, amount: 2330 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.GRIJS_LP_D, amount: 675 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.ZWART_LP_A, amount: 6670 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.WIT_LP_A, amount: 3161 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.WIT_LP_B, amount: 1023 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BLAUW_DD_A, amount: 534 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.PAARS_DD_A, amount: 854 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.PAARS_DD_B, amount: 500 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.TURQUOISE_BK_A, amount: 1099 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BLAUW_BK_A, amount: 1099 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BLAUW_BK_B, amount: 1099 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.BLAUW_BK_C, amount: 1114 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.PAARS_BK_A, amount: 1100 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.WIT_BK_A, amount: 399 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.WIT_BK_B, amount: 399 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.WIT_BK_C, amount: 399 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.WIT_BK_D, amount: 399 },
      { userId: idMap.users.WASILJA_PETERSE, stoneId: idMap.stones.WIT_BK_E, amount: 400 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.ROOD_LP_C, amount: 1114 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.ORANJE_LP_A, amount: 1016 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GEEL_LP_A, amount: 2064 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GEEL_LP_B, amount: 2199 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GROEN_LP_D, amount: 2034 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GROEN_LP_F, amount: 511 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.TURQUOISE_LP_A, amount: 1615 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.TURQUOISE_LP_B, amount: 1498 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.BLAUW_LP_A, amount: 1407 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.BLAUW_LP_E, amount: 2716 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.ROZE_LP_A, amount: 2545 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.ROZE_LP_E, amount: 916 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.IVOOR_LP_A, amount: 223 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.ZWART_LP_A, amount: 1060 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.WIT_LP_A, amount: 2413 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.WIT_LP_B, amount: 839 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.PAARS_DD_C, amount: 803 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GROEN_DD_A, amount: 213 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.ROOD_CC_A, amount: 625 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.ROZE_CC_A, amount: 442 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GEEL_CC_A, amount: 798 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GEEL_CC_B, amount: 670 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GEEL_CC_C, amount: 558 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GROEN_CC_A, amount: 573 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.GROEN_CC_B, amount: 467 },
      { userId: idMap.users.BART_VRIENS, stoneId: idMap.stones.WIT_MD_C, amount: 500 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.ROOD_LP_C, amount: 3039 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.ORANJE_LP_A, amount: 1779 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.GEEL_LP_B, amount: 2000 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.GROEN_LP_A, amount: 2731 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.GROEN_LP_B, amount: 4000 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.GROEN_LP_D, amount: 5000 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.BLAUW_LP_C, amount: 10061 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.BLAUW_LP_D, amount: 8632 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.BLAUW_LP_E, amount: 3530 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.PAARS_LP_C, amount: 5996 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.IVOOR_LP_B, amount: 3070 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.ZWART_LP_A, amount: 8193 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.WIT_LP_A, amount: 15803 },
      { userId: idMap.users.WIM_VAN_OTTERDIJK, stoneId: idMap.stones.WIT_LP_B, amount: 16096 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.ROOD_LP_C, amount: 7806 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.ORANJE_LP_A, amount: 3486 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.GEEL_LP_B, amount: 2014 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.GROEN_LP_D, amount: 4872 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.GROEN_LP_F, amount: 2061 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.BLAUW_LP_E, amount: 3743 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.PAARS_LP_C, amount: 817 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.IVOOR_LP_A, amount: 3024 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.BRUIN_LP_A, amount: 12753 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.BRUIN_LP_C, amount: 3083 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.GRIJS_LP_A, amount: 3048 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.ZWART_LP_A, amount: 6190 },
      { userId: idMap.users.JAAP_VERSCHUREN, stoneId: idMap.stones.WIT_LP_A, amount: 9823 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.ROOD_LP_C, amount: 1140 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.ORANJE_LP_A, amount: 535 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.GEEL_LP_B, amount: 1152 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.GROEN_LP_B, amount: 308 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.GROEN_LP_D, amount: 1127 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.BLAUW_LP_E, amount: 1188 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.ROZE_LP_C, amount: 614 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.BRUIN_LP_A, amount: 513 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.BRUIN_LP_C, amount: 768 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.ZWART_LP_A, amount: 1098 },
      // { userId: idMap.users.PABLO_VELT, stoneId: idMap.stones.WIT_LP_A, amount: 2072 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROOD_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROOD_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROOD_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROOD_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROOD_LP_E, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ORANJE_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ORANJE_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ORANJE_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ORANJE_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ORANJE_LP_E, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GEEL_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GEEL_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GEEL_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GROEN_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GROEN_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GROEN_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GROEN_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GROEN_LP_E, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GROEN_LP_F, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.TURQUOISE_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.TURQUOISE_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.TURQUOISE_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BLAUW_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BLAUW_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BLAUW_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BLAUW_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BLAUW_LP_E, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.PAARS_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.PAARS_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.PAARS_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.PAARS_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.PAARS_LP_E, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROZE_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROZE_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROZE_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROZE_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ROZE_LP_E, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.IVOOR_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.IVOOR_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.IVOOR_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.IVOOR_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BRUIN_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BRUIN_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BRUIN_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BRUIN_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.BRUIN_LP_E, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GRIJS_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GRIJS_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GRIJS_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.GRIJS_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ZWART_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.WIT_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.WIT_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.MIX_LP_A, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.MIX_LP_B, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.MIX_LP_C, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.MIX_LP_D, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.MIX_LP_E, amount: 1 },
      // { userId: idMap.users.PATRICK_SINNER, stoneId: idMap.stones.ORANJE_LP_F, amount: 1 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.ROOD_MD_A, amount: 153 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.ROOD_MD_B, amount: 153 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.ORANJE_MD_A, amount: 102 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.GEEL_MD_A, amount: 153 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.GROEN_MD_A, amount: 153 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.BLAUW_MD_A, amount: 153 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.PAARS_MD_A, amount: 153 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.PAARS_MD_B, amount: 51 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.ROZE_MD_A, amount: 102 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.WIT_MD_A, amount: 306 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.WIT_MD_B, amount: 153 },
      { userId: idMap.users.LISA_NEDERVEEN, stoneId: idMap.stones.ZWART_MD_A, amount: 204 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.ROOD_LP_A, amount: 529 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.ROOD_LP_C, amount: 2075 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.ROOD_LP_D, amount: 302 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.ORANJE_LP_B, amount: 306 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.GEEL_LP_B, amount: 675 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.GROEN_LP_B, amount: 525 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.GROEN_LP_C, amount: 146 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.GROEN_LP_D, amount: 530 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.BLAUW_LP_A, amount: 783 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.BLAUW_LP_D, amount: 300 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.BLAUW_LP_E, amount: 775 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.PAARS_LP_C, amount: 301 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.ROZE_LP_A, amount: 508 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.IVOOR_LP_C, amount: 584 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.BRUIN_LP_A, amount: 510 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.ZWART_LP_A, amount: 1350 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.WIT_LP_A, amount: 1030 },
      { userId: idMap.users.THOMAS_VAN_WELY, stoneId: idMap.stones.WIT_LP_B, amount: 611 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.ROOD_LP_A, amount: 101 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.ROOD_LP_C, amount: 203 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.ORANJE_LP_A, amount: 103 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.GEEL_LP_A, amount: 104 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.GEEL_LP_B, amount: 206 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.GROEN_LP_B, amount: 205 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.GROEN_LP_D, amount: 305 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.TURQUOISE_LP_B, amount: 104 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.BLAUW_LP_A, amount: 204 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.BLAUW_LP_E, amount: 103 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.PAARS_LP_C, amount: 104 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.ROZE_LP_A, amount: 204 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.ROZE_LP_C, amount: 104 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.BRUIN_LP_A, amount: 100 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.BRUIN_LP_C, amount: 104 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.GRIJS_LP_A, amount: 104 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.ZWART_LP_A, amount: 203 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.WIT_LP_A, amount: 305 },
      { userId: idMap.users.WOUT_DUTOIT, stoneId: idMap.stones.WIT_LP_B, amount: 208 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ROOD_LP_A, amount: 14623 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ROOD_LP_C, amount: 7848 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ORANJE_LP_A, amount: 13825 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ORANJE_LP_C, amount: 4000 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.GEEL_LP_A, amount: 7837 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.GEEL_LP_B, amount: 22064 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.GROEN_LP_B, amount: 9501 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.GROEN_LP_D, amount: 21450 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.TURQUOISE_LP_B, amount: 2028 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.BLAUW_LP_A, amount: 9300 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.BLAUW_LP_B, amount: 4269 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.BLAUW_LP_E, amount: 10933 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.PAARS_LP_A, amount: 2230 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.PAARS_LP_E, amount: 112 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ROZE_LP_C, amount: 5955 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ROZE_LP_D, amount: 2091 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.IVOOR_LP_A, amount: 38500 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.IVOOR_LP_D, amount: 479 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.IVOOR_LP_C, amount: 9236 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.BRUIN_LP_A, amount: 20715 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.BRUIN_LP_B, amount: 8567 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.BRUIN_LP_C, amount: 18070 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.BRUIN_LP_E, amount: 1454 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.GRIJS_LP_A, amount: 28771 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.GRIJS_LP_B, amount: 15262 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ZWART_LP_A, amount: 41156 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.WIT_LP_A, amount: 44829 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.MIX_LP_A, amount: 4667 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.MIX_LP_B, amount: 2094 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.MIX_LP_C, amount: 1174 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.MIX_LP_D, amount: 709 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.MIX_LP_E, amount: 1500 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.MIX_CC_A, amount: 1854 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ZWART_CC_A, amount: 1319 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ZWART_CC_B, amount: 605 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ZWART_CC_C, amount: 535 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ZWART_CC_D, amount: 219 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ZWART_CC_E, amount: 667 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ZWART_CC_F, amount: 486 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ZWART_CC_G, amount: 2818 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ZWART_CC_H, amount: 6071 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.WIT_CC_A, amount: 4741 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.WIT_CC_B, amount: 2879 },
      { userId: idMap.users.DDT_ADMIN, stoneId: idMap.stones.ROOD_CC_B, amount: 255 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ROOD_LP_A, amount: 100 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ROOD_LP_C, amount: 710 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ORANJE_LP_A, amount: 244 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ORANJE_LP_B, amount: 99 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.GEEL_LP_C, amount: 826 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.GROEN_LP_B, amount: 305 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.GROEN_LP_D, amount: 589 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.GROEN_LP_E, amount: 98 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.TURQUOISE_LP_A, amount: 147 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.TURQUOISE_LP_B, amount: 300 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.BLAUW_LP_A, amount: 455 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.BLAUW_LP_E, amount: 814 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.PAARS_LP_C, amount: 364 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ROZE_LP_A, amount: 53 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ROZE_LP_B, amount: 153 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ROZE_LP_C, amount: 303 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ROZE_LP_E, amount: 153 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.IVOOR_LP_A, amount: 718 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.BRUIN_LP_A, amount: 378 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.BRUIN_LP_B, amount: 230 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.BRUIN_LP_C, amount: 238 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.GRIJS_LP_A, amount: 363 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.GRIJS_LP_B, amount: 77 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.GRIJS_LP_C, amount: 100 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ZWART_LP_A, amount: 868 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.WIT_LP_A, amount: 2944 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.WIT_LP_B, amount: 464 },
      { userId: idMap.users.THOMAS_BOSBOOM, stoneId: idMap.stones.ORANJE_LP_F, amount: 178 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ROOD_LP_C, amount: 1223 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ROOD_LP_E, amount: 102 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ORANJE_LP_A, amount: 718 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.GEEL_LP_A, amount: 517 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.GEEL_LP_B, amount: 1240 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.GROEN_LP_B, amount: 1247 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.GROEN_LP_D, amount: 510 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.TURQUOISE_LP_B, amount: 507 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.BLAUW_LP_A, amount: 1242 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.BLAUW_LP_E, amount: 721 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.PAARS_LP_C, amount: 515 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ROZE_LP_A, amount: 827 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ROZE_LP_C, amount: 513 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.BRUIN_LP_A, amount: 732 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.BRUIN_LP_B, amount: 202 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.BRUIN_LP_C, amount: 612 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.GRIJS_LP_A, amount: 729 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.GRIJS_LP_C, amount: 102 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.GRIJS_LP_D, amount: 204 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ZWART_LP_A, amount: 1247 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.WIT_LP_A, amount: 1221 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.WIT_LP_B, amount: 765 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ROOD_MD_A, amount: 198 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ORANJE_MD_A, amount: 200 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.GEEL_MD_A, amount: 194 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.GROEN_MD_A, amount: 198 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.BLAUW_MD_A, amount: 196 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.PAARS_MD_A, amount: 199 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ROZE_MD_A, amount: 199 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.WIT_MD_A, amount: 199 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.WIT_MD_B, amount: 200 },
      { userId: idMap.users.SEPPE_LESENNE, stoneId: idMap.stones.ZWART_MD_A, amount: 200 },
      { userId: idMap.users.DON_DOMINO, stoneId: idMap.stones.ROOD_DO_A, amount: 2000 },
      { userId: idMap.users.DON_DOMINO, stoneId: idMap.stones.ROOD_DO_B, amount: 27000 },
      { userId: idMap.users.DON_DOMINO, stoneId: idMap.stones.GEEL_DO_A, amount: 2000 },
      { userId: idMap.users.DON_DOMINO, stoneId: idMap.stones.GEEL_DO_B, amount: 27000 },
      { userId: idMap.users.DON_DOMINO, stoneId: idMap.stones.GROEN_DO_C, amount: 21000 },
      { userId: idMap.users.DON_DOMINO, stoneId: idMap.stones.BLAUW_DO_B, amount: 40000 },
      { userId: idMap.users.DON_DOMINO, stoneId: idMap.stones.PAARS_DO_A, amount: 45000 },
      { userId: idMap.users.DON_DOMINO, stoneId: idMap.stones.ZWART_DO_A, amount: 1000 },
      { userId: idMap.users.DON_DOMINO, stoneId: idMap.stones.WIT_DO_A, amount: 1000 },
      // { userId: idMap.users.JOHANNES_LINNENBROEK, stoneId: idMap.stones.BRUIN_LP_B, amount: 6000 },
    ],
  });
}
