import { PrismaClient } from '@prisma/client';
import { idMap } from '@graphql/idMap';
import { hashPw } from '@lib/authHelpers';
import { generateSlug } from '@lib/util';

export default async function seedUsers(prisma: PrismaClient): Promise<void> {
  await prisma.user.createMany({
    data: [
      {
        id: idMap.users.DDT_ADMIN,
        firstName: 'DDT',
        lastName: 'Admin',
        displayName: 'DDT',
        slug: generateSlug('DDT'),
        email: 'info@dutchdominoteam.nl',
        password: await hashPw('Admin123'),
        isAdmin: true,
      },
      {
        id: idMap.users.WILLIAM_FORD,
        firstName: 'William',
        lastName: 'Ford',
        displayName: 'William F.',
        slug: generateSlug('William'),
        email: 'william.ford@telfort.nl',
        password: await hashPw('WilliamFord'),
        isAdmin: true,
      },
      {
        id: idMap.users.BAS_VEENHOVEN,
        firstName: 'Bas',
        lastName: 'Veenhoven',
        displayName: 'Bas V.',
        slug: generateSlug('Bas'),
        email: 'bas_veenhoven@hotmail.com',
        password: await hashPw('BasVeenhoven'),
        isAdmin: true,
      },
      {
        id: idMap.users.WASILJA_PETERSE,
        firstName: 'Wasilja',
        lastName: 'Peterse',
        displayName: 'Wasilja P.',
        slug: generateSlug('Wasilja'),
        email: 'wasilja_18@hotmail.com',
        password: await hashPw('WasiljaPeterse'),
      },
      {
        id: idMap.users.BART_VRIENS,
        firstName: 'Bart',
        lastName: 'Vriens',
        displayName: 'Bart V.',
        slug: generateSlug('Bart'),
        email: 'bart_vriens@live.nl',
        password: await hashPw('BartVriens'),
      },
      {
        id: idMap.users.PIM_VRIENS,
        firstName: 'Pim',
        lastName: 'Vriens',
        displayName: 'Pim V.',
        slug: generateSlug('Pim'),
        email: 'pim_vriens@hotmail.com',
        password: await hashPw('PimVriens'),
      },
      {
        id: idMap.users.WIM_VAN_OTTERDIJK,
        firstName: 'Wim',
        lastName: 'van Otterdijk',
        displayName: 'Wim v O.',
        slug: generateSlug('Wim'),
        email: 'w.v.otterdijk@gmail.com',
        password: await hashPw('WimVanOtterdijk'),
      },
      {
        id: idMap.users.JAAP_VERSCHUREN,
        firstName: 'Jaap',
        lastName: 'Verschuren',
        displayName: 'Jaap V.',
        slug: generateSlug('Jaap'),
        email: 'jaap_verschuren@hotmail.com',
      },
      {
        id: idMap.users.DON_DOMINO,
        firstName: 'Don',
        lastName: 'Domino',
        displayName: 'DonDomino',
        slug: generateSlug('Don'),
        email: 'info@dondomino.eu',
      },
      {
        id: idMap.users.THOMAS_VAN_WELY,
        firstName: 'Thomas',
        lastName: 'van Wely',
        displayName: 'Thomas v W.',
        slug: generateSlug('Thomas'),
        email: 'thomalio.v.wely@gmail.com',
        password: await hashPw('ThomasVanWely'),
      },
      {
        id: idMap.users.THOMAS_BOSBOOM,
        firstName: 'Thomas',
        lastName: 'Bosboom',
        displayName: 'Thomas B.',
        slug: generateSlug('Thomas'),
        email: 'thomasbosboom@hotmail.com',
        password: await hashPw('ThomasBosboom'),
      },
      {
        id: idMap.users.WOUT_DUTOIT,
        firstName: 'Wout',
        lastName: 'Dutoit',
        displayName: 'Wout D.',
        slug: generateSlug('Wout'),
        email: 'woutdutoit1@gmail.com',
        password: await hashPw('WoutDutoit'),
      },
      {
        id: idMap.users.SEPPE_LESENNE,
        firstName: 'Seppe',
        lastName: 'Lesenne',
        displayName: 'Seppe L.',
        slug: generateSlug('Seppe'),
        email: 'seppelesenne2003@gmail.com',
        password: await hashPw('SeppeLesenne'),
      },
      {
        id: idMap.users.LISA_NEDERVEEN,
        firstName: 'Lisa',
        lastName: 'Nederveen',
        displayName: 'Lisa N.',
        slug: generateSlug('Lisa'),
        email: 'nederveen.lisa@gmail.com',
        password: await hashPw('LisaNederveen'),
      },
    ],
  });
}
