import { PrismaClient, ProjectType } from '@prisma/client';
import { idMap } from '@graphql/idMap';
import { generateSlug } from '@lib/util';

export default async function seedProjectParts(prisma: PrismaClient): Promise<void> {
  await prisma.projectPart.createMany({
    data: [
      // WDC 2021
      {
        id: idMap.events.WDC_2021.INTRODUCTION.BOOK.DECOR,
        projectId: idMap.events.WDC_2021.INTRODUCTION.BOOK.id,
        name: 'Decor',
        slug: generateSlug('Decor'),
        number: 1,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.events.WDC_2021.INTRODUCTION.DON_DOMINO.FIELD,
        projectId: idMap.events.WDC_2021.INTRODUCTION.DON_DOMINO.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.INTRODUCTION.SINNERS.FIELD,
        projectId: idMap.events.WDC_2021.INTRODUCTION.SINNERS.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.INTRO.FIELD,
        projectId: idMap.events.WDC_2021.PETER_PAN.INTRO.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.FIELD,
        projectId: idMap.events.WDC_2021.PETER_PAN.FLYING_LONDON.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.NEVERLAND.STRUCTURE,
        projectId: idMap.events.WDC_2021.PETER_PAN.NEVERLAND.id,
        name: 'Structure',
        slug: generateSlug('Structure'),
        number: 1,
        type: ProjectType.STRUCTURE,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.FIELD,
        projectId: idMap.events.WDC_2021.PETER_PAN.TINKER_BELL.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MAP,
        projectId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.id,
        name: 'Schatkaart',
        slug: generateSlug('Schatkaart'),
        number: 1,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.INDIAN_VILLAGE,
        projectId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.id,
        name: 'Indian village',
        slug: generateSlug('Indian village'),
        number: 2,
        type: ProjectType.OTHER,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.MERMAIDS,
        projectId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.id,
        name: 'Mermaids',
        slug: generateSlug('Mermaids'),
        number: 3,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.SKULL_ISLAND,
        projectId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.id,
        name: 'Skull Island',
        slug: generateSlug('Skull Island'),
        number: 4,
        type: ProjectType.WALL_CUBE,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.FOOT_STEPS,
        projectId: idMap.events.WDC_2021.PETER_PAN.TREASURE_MAP.id,
        name: 'Foot Steps',
        slug: generateSlug('Foot Steps'),
        number: 5,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.DECOR,
        projectId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.id,
        name: 'Hiding Place',
        slug: generateSlug('Hiding Place'),
        number: 1,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.BEAR,
        projectId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.id,
        name: 'Bear',
        slug: generateSlug('Bear'),
        number: 2,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.SKUNK,
        projectId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.id,
        name: 'Skunk',
        slug: generateSlug('Skunk'),
        number: 3,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.FOX,
        projectId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.id,
        name: 'Fox',
        slug: generateSlug('Fox'),
        number: 4,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.RABBIT,
        projectId: idMap.events.WDC_2021.PETER_PAN.LOST_BOYS.id,
        name: 'Rabbit',
        slug: generateSlug('Rabbit'),
        number: 5,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.FIGHT.PETER_PAN,
        projectId: idMap.events.WDC_2021.PETER_PAN.FIGHT.id,
        name: 'Peter Pan',
        slug: generateSlug('Peter Pan'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.FIGHT.CAPTAIN_HOOK,
        projectId: idMap.events.WDC_2021.PETER_PAN.FIGHT.id,
        name: 'Captain Hook',
        slug: generateSlug('Captain Hook'),
        number: 2,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.FIGHT.CROCODILE,
        projectId: idMap.events.WDC_2021.PETER_PAN.FIGHT.id,
        name: 'Crocodile',
        slug: generateSlug('Crocodile'),
        number: 3,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.PETER_PAN.FLYING_SHIP.FIELD,
        projectId: idMap.events.WDC_2021.PETER_PAN.FLYING_SHIP.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.INTRO.FIELD,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.INTRO.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.CITY.POOR,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.CITY.id,
        name: 'Rich City',
        slug: generateSlug('Rich City'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.CITY.RICH,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.CITY.id,
        name: 'Poor City',
        slug: generateSlug('Poor City'),
        number: 2,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.DECOR,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.id,
        name: 'Dresser Decor',
        slug: generateSlug('Dresser Decor'),
        number: 1,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.SHIRT,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.id,
        name: 'Shirt',
        slug: generateSlug('Shirt'),
        number: 2,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.PANTS,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.id,
        name: 'Pants',
        slug: generateSlug('Pants'),
        number: 3,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.SOCKS,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.id,
        name: 'Socks',
        slug: generateSlug('Socks'),
        number: 4,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.JACKET,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.id,
        name: 'Jacket',
        slug: generateSlug('Jacket'),
        number: 5,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.HAT,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.DRESSER.id,
        name: 'Hat',
        slug: generateSlug('Hat'),
        number: 6,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.EMPEROR.FIELD,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.EMPEROR.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.EMPTY_FIELD,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.id,
        name: 'Empty Field',
        slug: generateSlug('Empty Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.SCISSORS,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.id,
        name: 'Scissors',
        slug: generateSlug('Scissors'),
        number: 2,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.PINCUSHION,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.id,
        name: 'Pincushion',
        slug: generateSlug('Pincushion'),
        number: 3,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.MEASURING_TAPE,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.id,
        name: 'Measuring Tape',
        slug: generateSlug('Measuring Tape'),
        number: 4,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.SPOOL_1,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.id,
        name: 'Spool 1',
        slug: generateSlug('Spool 1'),
        number: 5,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.SPOOL_2,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.TOOLS.id,
        name: 'Spool 2',
        slug: generateSlug('Spool 2'),
        number: 6,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.BACKGROUND_HOUSES,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.id,
        name: 'Background Houses',
        slug: generateSlug('Background Houses'),
        number: 1,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.BACKGROUND_LANDSCAPE,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.id,
        name: 'Background Landscape',
        slug: generateSlug('Background Landscape'),
        number: 2,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.SPECTATORS,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.id,
        name: 'Spectators',
        slug: generateSlug('Spectators'),
        number: 3,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.NAKED_EMPEROR,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.id,
        name: 'Naked Emperor',
        slug: generateSlug('Naked Emperor'),
        number: 4,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.KNIGHT,
        projectId: idMap.events.WDC_2021.EMPERORS_NEW_CLOTHES.PARADE.id,
        name: 'Knight',
        slug: generateSlug('Knight'),
        number: 5,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.INTRO.FIELD,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.INTRO.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.STAINED_GLASS.FIELD,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.STAINED_GLASS.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.ROSE.DECOR,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.ROSE.id,
        name: 'Decor',
        slug: generateSlug('Decor'),
        number: 1,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.JAIL.TRILOGY_1,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.JAIL.id,
        name: 'Dad Captive',
        slug: generateSlug('Dad Captive'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.JAIL.TRILOGY_2,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.JAIL.id,
        name: 'Belle Swapped',
        slug: generateSlug('Belle Swapped'),
        number: 2,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.JAIL.TRILOGY_3,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.JAIL.id,
        name: 'Belle Crying',
        slug: generateSlug('Belle Crying'),
        number: 3,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.CLOCK,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.id,
        name: 'Clock',
        slug: generateSlug('Clock'),
        number: 1,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.TEAPOT,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.id,
        name: 'Teapot',
        slug: generateSlug('Teapot'),
        number: 2,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.TEACUP,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.id,
        name: 'Teacup',
        slug: generateSlug('Teacup'),
        number: 3,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.PLUMEAU,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.id,
        name: 'Plumeau',
        slug: generateSlug('Plumeau'),
        number: 4,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.LUMIERE,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.id,
        name: 'Lumiere',
        slug: generateSlug('Lumiere'),
        number: 5,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.TABLE,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.id,
        name: 'Table',
        slug: generateSlug('Table'),
        number: 6,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.FOOD,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.DINNER.id,
        name: 'Food',
        slug: generateSlug('Food'),
        number: 7,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.TREES,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.id,
        name: 'Background Trees',
        slug: generateSlug('Background Trees'),
        number: 1,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.WOLVES_DECOR,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.id,
        name: 'Decor Wolves',
        slug: generateSlug('Decor Wolves'),
        number: 2,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.BEAST,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.id,
        name: 'Beast vs. Wolf',
        slug: generateSlug('Beast vs. Wolf'),
        number: 3,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.HEART,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.id,
        name: 'Heart',
        slug: generateSlug('Heart'),
        number: 4,
        type: ProjectType.FALLWALL,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.WOLF_1,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.id,
        name: 'Wolf 1',
        slug: generateSlug('Wolf 1'),
        number: 5,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.WOLF_2,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.id,
        name: 'Wolf 2',
        slug: generateSlug('Wolf 2'),
        number: 6,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.WOLF_3,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.FIGHT.id,
        name: 'Wolf 3',
        slug: generateSlug('Wolf 3'),
        number: 7,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.DANCE,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.id,
        name: 'Dancing',
        slug: generateSlug('Dancing'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.PILARS_DECOR,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.id,
        name: 'Pilars and Lint',
        slug: generateSlug('Pilars and Lint'),
        number: 2,
        type: ProjectType.DECOR,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.PILARS,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.id,
        name: 'Pilars Concealment',
        slug: generateSlug('Pilars Concealment'),
        number: 3,
        type: ProjectType.STRUCTURE,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.BACKGROUND,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.id,
        name: 'Background',
        slug: generateSlug('Background'),
        number: 4,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.FLOOR,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.id,
        name: 'Floor',
        slug: generateSlug('Floor'),
        number: 5,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.CHANDELIER,
        projectId: idMap.events.WDC_2021.BEAUTY_AND_THE_BEAST.BALLROOM.id,
        name: 'Chandelier',
        slug: generateSlug('Chandelier'),
        number: 6,
        type: ProjectType.DECOR,
      },

      // DDT 10 Years
      {
        id: idMap.events.DDT_10_YEARS.PROJECT.DDT_LOGO.FIELD,
        projectId: idMap.events.DDT_10_YEARS.PROJECT.DDT_LOGO.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.DDT_10_YEARS.PROJECT.FIREWORKS.SONIMOD,
        projectId: idMap.events.DDT_10_YEARS.PROJECT.FIREWORKS.id,
        name: 'Sonimod',
        slug: generateSlug('Sonimod'),
        number: 1,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.events.DDT_10_YEARS.PROJECT.FIREWORKS.TECHNIQUE,
        projectId: idMap.events.DDT_10_YEARS.PROJECT.FIREWORKS.id,
        name: 'Fireworks Technique',
        slug: generateSlug('Fireworks Technique'),
        number: 2,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.events.DDT_10_YEARS.PROJECT.TEN_YEARS.STRUCTURES,
        projectId: idMap.events.DDT_10_YEARS.PROJECT.TEN_YEARS.id,
        name: '3D Structures',
        slug: generateSlug('3D Structures'),
        number: 1,
        type: ProjectType.STRUCTURE,
      },
      {
        id: idMap.events.DDT_10_YEARS.PROJECT.PARTY_WALL.CERPENTINES,
        projectId: idMap.events.DDT_10_YEARS.PROJECT.PARTY_WALL.id,
        name: 'Cerpentines',
        slug: generateSlug('Cerpentines'),
        number: 1,
        type: ProjectType.HANDSET,
      },
      {
        id: idMap.events.DDT_10_YEARS.PROJECT.PARTY_WALL.WALL,
        projectId: idMap.events.DDT_10_YEARS.PROJECT.PARTY_WALL.id,
        name: 'Wall',
        slug: generateSlug('Wall'),
        number: 2,
        type: ProjectType.WALL_X,
      },
      {
        id: idMap.events.DDT_10_YEARS.PROJECT.FINAL.FIELD,
        projectId: idMap.events.DDT_10_YEARS.PROJECT.FINAL.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },

      // VEXX
      {
        id: idMap.events.VEXX.PROJECT.WIX_LOGO.FIELD,
        projectId: idMap.events.VEXX.PROJECT.WIX_LOGO.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.VEXX.PROJECT.DOODLE.FIELD,
        projectId: idMap.events.VEXX.PROJECT.DOODLE.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.VEXX.PROJECT.CAMPBELL.FIELD,
        projectId: idMap.events.VEXX.PROJECT.CAMPBELL.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.VEXX.PROJECT.CAMPBELL.FALLWALL,
        projectId: idMap.events.VEXX.PROJECT.CAMPBELL.id,
        name: 'Fallwall',
        slug: generateSlug('Fallwall'),
        number: 2,
        type: ProjectType.FALLWALL,
      },
      {
        id: idMap.events.VEXX.PROJECT.MATISSE.FIELD,
        projectId: idMap.events.VEXX.PROJECT.MATISSE.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.VEXX.PROJECT.MATISSE.FALLWALL,
        projectId: idMap.events.VEXX.PROJECT.MATISSE.id,
        name: 'Fallwall',
        slug: generateSlug('Fallwall'),
        number: 2,
        type: ProjectType.FALLWALL,
      },
      {
        id: idMap.events.VEXX.PROJECT.VAN_GOGH.FIELD,
        projectId: idMap.events.VEXX.PROJECT.VAN_GOGH.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.VEXX.PROJECT.VAN_GOGH.FALLWALL,
        projectId: idMap.events.VEXX.PROJECT.VAN_GOGH.id,
        name: 'Fallwall',
        slug: generateSlug('Fallwall'),
        number: 2,
        type: ProjectType.FALLWALL,
      },
      {
        id: idMap.events.VEXX.PROJECT.ELMO.FIELD,
        projectId: idMap.events.VEXX.PROJECT.ELMO.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
      {
        id: idMap.events.VEXX.PROJECT.SPONGEBOB.FIELD,
        projectId: idMap.events.VEXX.PROJECT.SPONGEBOB.id,
        name: 'Field',
        slug: generateSlug('Field'),
        number: 1,
        type: ProjectType.FIELD_L2,
      },
    ],
  });
}
