name: Main CD

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  main_cd:
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Add DotEnv Variables
        run: printf 'DATABASE_URL=${{ secrets.DATABASE_URL_MAIN }}' > .env
      - name: Install dependencies
        run: yarn
      # - name: Generate GraphQL Types
      #   run: |
      #     yarn prisma:generate
      #     yarn nexus:generate
      - name: Lint
        run: yarn lint:api
      # - name: Update Database
      #   run: yarn mig:deploy
